<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agama' => '',
    'Alamat KTP' => '',
    'Alamat Tinggal' => '',
    'Createtime' => '',
    'Createuser' => '',
    'Deletedtime' => '',
    'Deleteduser' => '',
    'Email' => '',
    'Email Pribadi' => '',
    'ID' => '',
    'Isdeleted' => '',
    'Jenis' => '',
    'Jenis Kelamin' => '',
    'Jumlah Tanggungan Pajak' => '',
    'Kecamatan KTP' => '',
    'Kecamatan Tinggal' => '',
    'Kelurahan KTP' => '',
    'Kelurahan Tinggal' => '',
    'Kode Dokter Gigi BPJS' => '',
    'Kode Faskes 1 BPJS' => '',
    'Kota KTP' => '',
    'Kota Tinggal' => '',
    'Modifiedtime' => '',
    'Modifieduser' => '',
    'NPWP' => '',
    'Nama' => '',
    'Nama Dokter Gigi BPJS' => '',
    'Nama Faskes 1 BPJS' => '',
    'Nip' => '',
    'No KTP' => '',
    'Nomor BPJS' => '',
    'Nomor HP' => '',
    'Nomor Rekening' => '',
    'Status Aktif' => '',
    'Status Nikah' => '',
    'Status Nikah Pajak' => '',
    'Tanggal Akhir Kontrak' => '',
    'Tanggal Lahir' => '',
    'Tanggal Masuk Kerja' => '',
    'Tanggal Mulai Kontrak' => '',
    'Tanggal Pengangkatan' => '',
    'Telepon' => '',
    'Tempat Lahir' => '',
    'Userid' => '',
];
