<?php
    /**
     * Configuration file for 'yii message/extract' command.
     *
     * This file is automatically generated by 'yii message/config' command.
     * It contains parameters for source code messages extraction.
     * You may modify this file to suit your needs.
     *
     * You can use 'yii message/config-template' command to create
     * template configuration file with detailed description for each parameter.
     */
    return [
        'color'              => NULL,
        'interactive'        => TRUE,
        'help'               => NULL,
        'sourcePath'         => '@app',
        'messagePath'        => '@app/messages',
        'languages'          => ['id-ID', 'en-US'],
        'translator'         => 'Yii::t',
        'sort'               => TRUE,
        'overwrite'          => TRUE,
        'removeUnused'       => TRUE,
        'markUnused'         => TRUE,
        'except'             => [
            '.svn',
            '.git',
            '.gitignore',
            '.gitkeep',
            '.hgignore',
            '.hgkeep',
            '/messages',
            '/vendor',
            '/assets',
            '/runtime',
            '/tests',
            '/web',
            '/BaseYii.php',
        ],
        'only'               => [
            '*.php',
        ],
        'format'             => 'php',
        'db'                 => 'db',
        'sourceMessageTable' => '{{%source_message}}',
        'messageTable'       => '{{%message}}',
        'catalog'            => 'messages',
        'ignoreCategories'   => [],
        'phpFileHeader'      => '',
        'phpDocBlock'        => NULL
    ];
